FROM fedora:42 
WORKDIR /usr/local/course

RUN dnf install -y python ansible python3-github3py python3-rpm git make gmp-devel just fish

# run by hand (produces big image):
# ansible-playbook playbooks/setup.yml
