# TODO: update shell with just
# eval $(opam env --switch=default)

help:
 just -l

build TASK_ID:
 just task{{TASK_ID}}/build

test TASK_ID:
 just task{{TASK_ID}}/test

build_all:
 dune build

test_all:
 dune test
